# Generated by Django 4.0.6 on 2022-07-08 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_alter_workout_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercisetype',
            old_name='distanceincluded',
            new_name='distance',
        ),
        migrations.RenameField(
            model_name='exercisetype',
            old_name='durationincluded',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='exercisetype',
            old_name='elevationincluded',
            new_name='elevation',
        ),
        migrations.RenameField(
            model_name='exercisetype',
            old_name='repsincluded',
            new_name='reps',
        ),
        migrations.RenameField(
            model_name='exercisetype',
            old_name='weightsincluded',
            new_name='weights',
        ),
    ]
