# Generated by Django 4.0.6 on 2022-07-24 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_rename_distanceincluded_exercisetype_distance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisetype',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='exercisetype',
            unique_together={('name', 'category')},
        ),
    ]
