# Generated by Django 4.0.6 on 2022-07-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_alter_exercisetype_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisetype',
            name='date',
            field=models.DateTimeField(default=0),
            preserve_default=False,
        ),
    ]
