# Generated by Django 4.0.6 on 2022-08-05 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0006_exercise_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercisetype',
            old_name='weights',
            new_name='weight',
        ),
    ]
