# Generated by Django 4.0.6 on 2022-07-25 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0006_exercisetype_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercisetype',
            name='date',
        ),
        migrations.AddField(
            model_name='exercise',
            name='date',
            field=models.DateTimeField(default='0'),
            preserve_default=False,
        ),
    ]
