# Generated by Django 4.0.6 on 2022-08-05 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0007_rename_weights_exercisetype_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='assisted',
            field=models.BooleanField(default=False),
        ),
    ]
