# Generated by Django 4.0.6 on 2022-08-06 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0010_exercisetype_assisted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercisetype',
            old_name='assisted',
            new_name='assisted_option',
        ),
    ]
