# Generated by Django 4.0.6 on 2022-09-09 01:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0012_workout_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
